### PR TITLE
Adding development environment setup doc

### PR DESCRIPTION
**Pull request by font**
This is an initial draft for creating a documented development environment setup for working on secure supply chain.

### CODE REVIEW

**Comment by lukehinds** [comment]
Thanks @font , let me run through this locally and then I can feed back in review.

**Comment by lukehinds** [comment]
@mbestavros / @mpeters @axelsimon you might be interested to take this for a drive, should only take around 5-10 mins and can easily run on a laptop.

**Comment by lukehinds** [comment]
A bit of feedback @font 

Might be obvious, but you need to be logged into docker.io first:


I am also hitting this issue, but I pretty sure that's not the fault of your script

```
./kind-reg.sh
Unable to find image 'registry:2' locally
2: Pulling from library/registry
486039affc0a: Pull complete 
ba51a3b098e6: Pull complete 
8bb4c43d6c8e: Pull complete 
6f5f453e5f2d: Pull complete 
42bc10b72f42: Pull complete 
Digest: sha256:7d081088e4bfd632a88e3f3bcd9e007ef44a796fddfe3261407a3f9f04abe1e7
Status: Downloaded newer image for registry:2
059cbe0539b318a0f65805dc31ead474c015b757a14113afa53cd0c2893edc1f
docker: Error response from daemon: driver failed programming external connectivity on endpoint registry (24432bac5de4d75acee4d9a105ac728408fa1e85c7acfd608ed902f600807aab):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 5000 -j DNAT --to-destination 172.17.0.2:5000 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1)).
```

**Comment by font** [comment]
Thanks @lukehinds! I've added a comment about `docker login`. Regarding your `iptables` `nat` table not containing the `DOCKER` target, it seems this https://github.com/moby/moby/issues/16816 may be useful. What version of `docker` are you running? How was it installed? Are you using `iptables`? You may need to upgrade `docker` and/or try restarting `iptables` and the `docker` daemon.

**Comment by lukehinds** [comment]
hi @font 

I got through the whole doc now, everything appeared to work well, but I am hitting a connection issue. Seems related to a webhook:

```
~/bin/tkn pipeline list
NAME              AGE             LAST RUN   STARTED   DURATION   STATUS
sample-pipeline   9 minutes ago   ---        ---       ---        ---

~/bin/tkn pipelinerun logs -f sample-pipeline-run

E0516 02:07:20.829109   48544 reflector.go:123] pkg/mod/k8s.io/client-go@v0.16.5/tools/cache/reflector.go:96: Failed to list *v1alpha1.PipelineRun: conversion webhook for tekton.dev/v1beta1, Kind=PipelineRun failed: Post https://tekton-pipelines-webhook.tekton-pipelines.svc:443/?timeout=30s: dial tcp 10.96.143.60:443: connect: connection refused
```

**Comment by font** [comment]
@lukehinds 
> I got through the whole doc now, everything appeared to work well, but I am hitting a connection issue. Seems related to a webhook:

What version of `tkn` are you using? It looks like you may be using an older version of the `tkn` CLI as it is requesting a `v1alpha1` version of the `PipelineRun` resource while Tekton has recently updated the storage version of their APIs from `v1alpha1` to `v1beta1` and there is no conversion webhook to handle the version drift. This may be expected if you're installing a development version of Tekton e.g. `master@HEAD`, that may be incompatible with older versions of other components like the `tkn` CLI. If updating the `tkn` CLI doesn't fix this, try working with compatible versions of both components such as using the last release of each component to get a known working combination.

**Comment by lukehinds** [comment]
@font 

From a cursory look I have the latest tkn client

```
$ tkn version
Client version: 0.9.0
```

The version of tkn is the one in Dan's fork on the validate branch. How would I find the version from that?

**Comment by font** [comment]
> From a cursory look I have the latest tkn client
> 
> ```
> $ tkn version
> Client version: 0.9.0
> ```
> 
> The version of tekton pipelines is the one in Dan's fork on the validate branch. How would I find the version from that?

@lukehinds The `tkn version` command *should* output the version. For example a released version you should see something like:

```shell
→ tkn version
Client version: 0.9.0
Pipeline version: v0.12.1
```

Unless of course it's not a released version, in which case it's *supposed* to output `devel`. But apparently a bug is preventing that as for a non-released version e.g. `HEAD`, I get:

```shell
→ tkn version
Client version: 0.9.0
Pipeline version: unknown
```

Even if it correctly outputted `devel`, it's not very useful as ideally it would be an exact git commit hash relative to the last official release. Perhaps that's an enhancement I should add.

In any case, for now I'm not sure there's a way to validate the version aside from being a bit of an archaeologist in your repo and branch to assess what commits are being used relative to the last known released version.

**Comment by mpeters** [comment]
@font would you be able to merge this? would make it slightly easier to fork and try out

**Comment by lukehinds** [comment]
> @font would you be able to merge this? would make it slightly easier to fork and try out

all done

**Comment by mpeters** [comment]
@lukehinds how did you get past the reflection/connection error? I'm hitting the same problem now. I installed tkn from their rpm on https://github.com/tektoncd/cli

```
$ tkn version
Client version: 0.9.0
Pipeline version: unknown
```
It should be the most recent release. But I still get:

```
$ tkn pipelinerun logs -f sample-pipeline-run
E0528 10:34:22.558051   31808 reflector.go:123] pkg/mod/k8s.io/client-go@v0.16.5/tools/cache/reflector.go:96: Failed to list *v1alpha1.PipelineRun: conversion webhook for tekton.dev/v1beta1, Kind=PipelineRun failed: Post https://tekton-pipelines-webhook.tekton-pipelines.svc:443/?timeout=30s: dial tcp 10.105.222.106:443: connect: connection refused
```

I tried deleting the kind cluster and reconfiguring everything, but the same results.

**Comment by font** [comment]
> @lukehinds how did you get past the reflection/connection error? I'm hitting the same problem now. I installed tkn from their rpm on https://github.com/tektoncd/cli
> 
> ```
> $ tkn version
> Client version: 0.9.0
> Pipeline version: unknown
> ```
> 
> It should be the most recent release. But I still get:
> 
> ```
> $ tkn pipelinerun logs -f sample-pipeline-run
> E0528 10:34:22.558051   31808 reflector.go:123] pkg/mod/k8s.io/client-go@v0.16.5/tools/cache/reflector.go:96: Failed to list *v1alpha1.PipelineRun: conversion webhook for tekton.dev/v1beta1, Kind=PipelineRun failed: Post https://tekton-pipelines-webhook.tekton-pipelines.svc:443/?timeout=30s: dial tcp 10.105.222.106:443: connect: connection refused
> ```
> 
> I tried deleting the kind cluster and reconfiguring everything, but the same results.

@mpeters are you deploying from https://github.com/tektoncd/pipeline `master@HEAD` or some other fork/branch? If so, what git commit hash are you deploying with? If you haven't already, try the latest `master@HEAD` or the last official tekton pipeline release.

**Comment by mpeters** [comment]
@font Nothing fancy, I just forked https://github.com/tektoncd/pipeline to https://github.com/mpeters/pipeline and put it in `/home/mpeters/go/src/github.com/tektoncd/pipeline`. I even just refreshed my fork against upstream master right now to check that nothing was wrong. This is on my new RHEL laptop so no previous versions of Tekton, tk, kind or anything else. Just the latest versions of all of it.

**Comment by lukehinds** [comment]
I am hitting the same again (using upstream master). I figured this out before and my bad I did not take a note. 

One observation, I see this at the beginning of the stdout from `ko apply -f config`

`2020/05/29 11:15:38 No matching credentials were found, falling back on anonymous`

**Comment by lukehinds** [comment]
https://github.com/tektoncd/pipeline/issues/2207#issuecomment-635944256

**Comment by lukehinds** [comment]
A little more, hitting the same issue using master branch of pipelines and master tkn branch, so its not a version discrepancy from what I can see:

```
$ tkn version
Client version: dev
Pipeline version: devel
Triggers version: unknown
```

**Pull request merged**
